# Generated by Django 5.1 on 2024-08-23 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FrontendApp', '0003_caloriedb_calorie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caloriedb',
            name='calorie',
            field=models.IntegerField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='caloriedb',
            name='height',
            field=models.IntegerField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='caloriedb',
            name='weight',
            field=models.IntegerField(blank=True, max_length=100, null=True),
        ),
    ]
