# Generated by Django 5.1 on 2024-08-23 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FrontendApp', '0004_alter_caloriedb_calorie_alter_caloriedb_height_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caloriedb',
            name='age',
            field=models.IntegerField(blank=True, max_length=100, null=True),
        ),
    ]
