# Generated by Django 5.1 on 2024-08-23 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FrontendApp', '0005_alter_caloriedb_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caloriedb',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='caloriedb',
            name='calorie',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='caloriedb',
            name='height',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='caloriedb',
            name='weight',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='signupdb',
            name='height',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='signupdb',
            name='weight',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
