# Generated by Django 5.1 on 2024-08-29 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FrontendApp', '0007_number_basis_fooddb'),
    ]

    operations = [
        migrations.AddField(
            model_name='signupdb',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='signupdb',
            name='calorie_intake',
            field=models.IntegerField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='signupdb',
            name='gender',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
