# Generated by Django 5.1 on 2024-08-29 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FrontendApp', '0009_nutrientsdb'),
    ]

    operations = [
        migrations.DeleteModel(
            name='nutrientsDB',
        ),
    ]
