# Generated by Django 5.1 on 2024-08-30 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FrontendApp', '0010_delete_nutrientsdb'),
    ]

    operations = [
        migrations.CreateModel(
            name='item_addedDB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_added', models.CharField(blank=True, max_length=100, null=True)),
                ('calorie_added', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
