# Generated by Django 5.1 on 2024-08-30 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FrontendApp', '0011_item_addeddb'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item_addeddb',
            name='calorie_added',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
