# Generated by Django 5.1 on 2024-08-30 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FrontendApp', '0012_alter_item_addeddb_calorie_added'),
    ]

    operations = [
        migrations.AddField(
            model_name='item_addeddb',
            name='hiddenusername',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
