# Generated by Django 5.1 on 2024-08-30 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FrontendApp', '0013_item_addeddb_hiddenusername'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item_addeddb',
            old_name='hiddenusername',
            new_name='username',
        ),
    ]
