# Generated by Django 5.1 on 2024-08-30 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FrontendApp', '0014_rename_hiddenusername_item_addeddb_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='item_addeddb',
            name='calorie_intake',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='signupdb',
            name='calorie_intake',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
