# Generated by Django 5.1 on 2024-09-04 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FrontendApp', '0015_item_addeddb_calorie_intake_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item_addeddb',
            name='datepicker',
            field=models.DateField(blank=True, max_length=250, null=True),
        ),
    ]
