# Generated by Django 5.1 on 2024-09-20 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FrontendApp', '0017_datedb'),
    ]

    operations = [
        migrations.AddField(
            model_name='datedb',
            name='username',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
