# Generated by Django 5.1 on 2024-09-20 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FrontendApp', '0018_datedb_username'),
    ]

    operations = [
        migrations.DeleteModel(
            name='dateDB',
        ),
    ]
