# Generated by Django 5.1 on 2024-09-20 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FrontendApp', '0019_delete_datedb'),
    ]

    operations = [
        migrations.AddField(
            model_name='item_addeddb',
            name='quantity',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
