# Generated by Django 5.1 on 2024-09-20 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FrontendApp', '0020_item_addeddb_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item_addeddb',
            name='quantity',
        ),
    ]
