# Generated by Django 5.1 on 2024-09-21 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FrontendApp', '0021_remove_item_addeddb_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='item_addeddb',
            name='quantity',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
