# Generated by Django 5.1 on 2024-09-25 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FrontendApp', '0023_item_addeddb_total_calorie'),
    ]

    operations = [
        migrations.CreateModel(
            name='final_dataDB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=100, null=True)),
                ('total', models.IntegerField(blank=True, null=True)),
                ('day', models.DateField(blank=True, max_length=250, null=True)),
            ],
        ),
    ]
