# Generated by Django 5.1 on 2024-09-25 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FrontendApp', '0024_final_datadb'),
    ]

    operations = [
        migrations.AlterField(
            model_name='final_datadb',
            name='total',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
