# Generated by Django 5.1 on 2024-09-26 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FrontendApp', '0025_alter_final_datadb_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='final_datadb',
            name='day',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='final_datadb',
            name='total',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
