# Generated by Django 5.1 on 2024-08-25 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BackendApp', '0003_number_basis_fooddb'),
    ]

    operations = [
        migrations.CreateModel(
            name='number_basis_calorieDB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(blank=True, max_length=100, null=True)),
                ('small', models.IntegerField(blank=True, null=True)),
                ('medium', models.IntegerField(blank=True, null=True)),
                ('large', models.IntegerField(blank=True, null=True)),
                ('item_image', models.ImageField(blank=True, null=True, upload_to='item_images')),
            ],
        ),
    ]
