# Generated by Django 5.1 on 2024-08-29 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BackendApp', '0005_nutrientsdb'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nutrientsdb',
            name='calorie',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='nutrientsdb',
            name='carbohydrates',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='nutrientsdb',
            name='fat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='nutrientsdb',
            name='fiber',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='nutrientsdb',
            name='protein',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
