# Generated by Django 5.1 on 2024-08-29 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BackendApp', '0006_alter_nutrientsdb_calorie_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='nutrientsdb',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='nutrientimg'),
        ),
    ]
